#http://localhost:8080/api-docs/

openapi: 3.0.0
docExpansion: '`none`'
info:
  title: Trackyo BE
  description: API for all routes
  version: 1.0.0
  contact:
    email: "xxxxxxxxx@gmail.com"
    url: "xxxxxxxxxx"
servers:
  - url: http://localhost:6000/api

 
    # description:       Optional server description, e.g. Internal staging server for testing
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      securityDefinitions:
paths:
  /calls/start:
    post:
      tags:
        - twilio
      summary: twilio
      requestBody:
        description: twilio description to make call and message
        content:
          application/json:
            schema:
                type: object
                example: 
                    {
                        "from":"+91XXXXXXXXXX",
                        "to":"+91XXXXXXXXXX",
                      }
      security: 
         - BearerAuth: []  
      responses:
        '200':    # status code
          description: A JSON array of content
          content:
            application/json:
              schema: 
                type: object
                example: 
                    {}
        '400':
          description: bad request    
  
