#http://localhost:8080/api-docs/

openapi: 3.0.0
docExpansion: '`none`'
info:
  title: Trackyo BE
  description: API for all routes
  version: 1.0.0
  contact:
    email: "xxxxxxxxx@gmail.com"
    url: "xxxxxxxxxx"
servers:
  - url: http://localhost:6001/api 

 
    # description:       Optional server description, e.g. Internal staging server for testing
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      securityDefinitions:
paths:
  /calls/start:
    post:
      tags:
        - exotel
      summary: Generate exotel number to connect QR owner .
      requestBody:
        description: exotel description 
        content:
          application/json:
            schema:
                type: object
                example: 
                    {
                        "fromNumber": 81XXXXXXXX,
                        "fromCountryCode": "+91",
                        "qrCode": "QR17212188301530",
                      }
      security: 
         - BearerAuth: []  
      responses:
        '200':    # status code
          description: A JSON array of content
          content:
            application/json:
              schema: 
                type: object
                example: 
                    {
                        "virtualNumber": "04954265711",
                        "callLogId": "66b0f2f846ace1e87343856b",
                    }
        '400':
          description: bad request    
  
